url: https://turtle2007.github.io
baseurl: /CHI22-ihfs/

# Site settings
title: CHI2022WORKSHOP
email: ifhs.chi2022@gmail.com
description: "Welcom to the CHI2022 workshop: Integration of Human Factors in Surgery: interdisciplinary collaboration in design, development, and evaluation of surgical technologies."



# Team names, titles and social links
people:
- name: Roman Bednarik
  pic: 1
  position: University of Eastern Finland
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Ann Blandford
  pic: 2
  position: University College London
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Feng Feng
  pic: 3
  position: University of Eastern Finland
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Antti Huotarinen
  pic: 4
  position: Kuopio University Hospital
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Matti Iso-Mustajärivi
  pic: 5
  position: Kuopio University Hospital
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Ahreum Lee
  pic: 6
  position: University of Eastern Finland
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Federico Nicolosi
  pic: 7
  position: UpsurgeOn
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Jeremy Opie
  pic: 8
  position: University College London
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Soojeong Yoo
  pic: 9
  position: University College London
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Bin Zheng
  pic: 10
  position: University of Alberta
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty