url: https://turtle2007.github.io
baseurl: /CHI22-ihfs/

# Site settings
title: CHI2022IHFS
email: ifhs.chi2022@gmail.com
description: "Welcom to the CHI2022 workshop: Integration of Human Factors in Surgery: interdisciplinary collaboration in design, development, and evaluation of surgical technologies."



# Team names, titles and social links
people:
- name: Roman Bednarik
  pic: 1
  position: University of Eastern Finland
  social:
    - title: twitter
      url:  http://twitter.com/RomanBednarik

- name: Ann Blandford
  pic: 2
  position: University College London
  social:
    - title: twitter
      url:  http://twitter.com/annblandford
    - title: linkedin
      url: https://www.linkedin.com/in/ann-blandford-01586a2/?originalSubdomain=uk

- name: Feng Feng
  pic: 3
  position: University of Eastern Finland
  social:
    - title: twitter
      url: http://twitter.com/Feng58486062
    - title: linkedin
      url: https://www.linkedin.com/in/feng-feng-308054146/
    - title: user
      url: https://fengxiwu.org/

- name: Antti Huotarinen
  pic: 4
  position: Kuopio University Hospital
  # social:

- name: Matti Iso-Mustajärivi
  pic: 5
  position: Kuopio University Hospital
  # social:

- name: Ahreum Lee
  pic: 6
  position: University of Eastern Finland
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/ahreum/
    - title: twitter
      url: http://twitter.com/l_ahreum
    - title: user
      url: ahreumlee.me

- name: Federico Nicolosi
  pic: 7
  position: UpsurgeOn
  social:
    - title: twitter
      url: http://twitter.com/fednicolosi

- name: Jeremy Opie
  pic: 8
  position: University College London
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jeremy-opie-6a27a096/

- name: Soojeong Yoo
  pic: 9
  position: University College London
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/soojeong-yoo-81b59784/
    - title: twitter
      url: http://twitter.com/YooSoojeong

- name: Bin Zheng
  pic: 10
  position: University of Alberta
  social:
    - title: user
      url: https://www.ualberta.ca/medicine/about/people/details.html?n=bin-zheng



# Postal address (add as many lines as necessary)
address:
  - line: Science Park
  - line: Joensuu, 80110

# Build settings
markdown: kramdown
permalink: pretty